### ISSUE TITLE
Could not get installed app list

### ISSUE THREAD

**Issue by Le0xFF** [casualsnek/cassowary#6] opened 2022-01-21 21:36 UTC
After connecting to the VM and then switching to the **Guest Apps** tab, I get the error that "Could not get installed app list from the server due to timeout".

What should I do?
![Error](https://user-images.githubusercontent.com/43521247/150603313-93987ab1-8184-4e73-97f3-053c9908c75e.png)

**Comment by casualsnek** [comment] 2022-01-22 03:33
Can you switch to other tabs without error, if you can you look into   C:\\Users\\username\\.config\\casualrdh\\

There should be a log file !

**Comment by Le0xFF** [comment] 2022-01-22 10:28
Yes I can switch to other tabs without any problem.
I just boot the VM and then run cassowary, so i don't login at all in the VM!
I tried to create a path to Windows (in the Linux -> Windows tab but all I get is a system error 87, parameter not correct)

Here's also the error log

**Comment by casualsnek** [comment] 2022-01-22 11:15
> Here's also the error log [casualrdh.log](https://github.com/casualsnek/cassowary/files/7918128/casualrdh.log)

Which windows and build number are you using, can you open registry editor and browse to ```HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths``` then attach a screenshot of it !

**Comment by Le0xFF** [comment] 2022-01-22 12:23
> browse to `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` then attach a screenshot of it!
![AppPath](https://user-images.githubusercontent.com/43521247/150638085-2152f190-0a5a-411f-95f5-91341931d13c.png)

> Which windows and build number are you using
![WinVer](https://user-images.githubusercontent.com/43521247/150638103-9fd4b80b-1974-4ccd-8527-38b2917453d9.png)
I already used the same Windows build with WinApps without any issue.

> `python3 -m cassowary -c guest-run -- "explorer.exe"`
It open Windows explorer without any issues and from there I can also see my Linux root from there
![Explorer](https://user-images.githubusercontent.com/43521247/150638376-ffe66511-e1f9-43cb-aef8-2c4da596283d.png)

**Comment by casualsnek** [comment] 2022-01-22 12:23
> Yes I can switch to other tabs without any problem. I just boot the VM and then run cassowary, so i don't login at all in the VM! I tried to create a path to Windows (in the Linux -> Windows tab) but all I get is a system error 87, parameter not correct
> 
> Here's also the error log [casualrdh.log](https://github.com/casualsnek/cassowary/files/7918128/casualrdh.log)

The issue will fixed, this was because you are not using english as language, dumb mistake on my part.. Should be fixed on next release that will be done by tonight !

Program looks for error with "[WinError 2] The system cannot find the file specified" to safely ignore but since you are non english it said "[WinError 2] Impossibile trovare il file specificato" which let the exception happen and crashed 😆

**Comment by Le0xFF** [comment] 2022-01-22 12:24
Fair enough, nice to know! So to fix my problem will I just have to install the new .whl file?

**Comment by casualsnek** [comment] 2022-01-22 12:28
> Fair enough, nice to know! So to fix my problem will I just have to install the new .whl file?

Yes and also download the windows setup of newer release and run setup.bat.. Then logout and it should work


For the second issue "Linux->Windows" Tab is for Making a location on host appear as Local Disk in VM, I suppose you chose "C" as drive letter which already exists in windows and therefore the crash.. Use another drive letter and it should work !

**Comment by Le0xFF** [comment] 2022-01-22 12:40
> I suppose you chose "C" as drive letter

No, I choose "B" as drive letter, but anyway I'll test it again with the upcoming release and I'll eventually update this issue!

**Comment by casualsnek** [comment] 2022-01-22 12:46
> > I suppose you chose "C" as drive letter
> 
> No, I choose "B" as drive letter, but anyway I'll test it again with the upcoming release and I'll eventually update this issue!

Local Disk B is reserved for floppy drives... Go few letters down lol

**Comment by Le0xFF** [comment] 2022-01-22 12:48
I tried a couple of different letters, such as `P` and `L`, but always same results.
![FolderMapping](https://user-images.githubusercontent.com/43521247/150639127-8a29bbaf-fcdb-4f0e-97be-e974100058d9.png)

**Comment by casualsnek** [comment] 2022-01-22 12:51
Are you using any app launched with cassowary while doing this ? If Not open explorer with ```python3 -m cassowary -c guest-run -- "explorer.exe"``` do not close explorer and try this again !, This share is only available while app is running through cassowary session not standard login !

**Comment by Le0xFF** [comment] 2022-01-22 12:56
Sadly same error even with explorer.exe open :(
![Error2](https://user-images.githubusercontent.com/43521247/150639404-ca447ea7-acf6-4e95-80b5-bb9e115a19a7.png)

**Comment by casualsnek** [comment] 2022-01-22 13:02
looks like even Z:\ is not mapped... there must be something wrong
can you open powershell with ``` python3 -m cassowary -c guest-run -- "powershell.exe" ```
and run ``` net use Z: \\\\tsclient\\root /persistent:Yes ```  and post the output

**Comment by Le0xFF** [comment] 2022-01-22 13:17
> looks like even Z:\ is not mapped
It seems it's mapped only when I open explorer.exe, as you can see from the image.

> `net use Z: \\tsclient\root /persistent:Yes`
![Uploading Powershell.png…]()

**Comment by casualsnek** [comment] 2022-01-22 13:35
> > looks like even Z:\ is not mapped
> 
> It seems it's mapped only when I open explorer.exe, as you can see from the image.
> 
> > `net use Z: \\tsclient\root /persistent:Yes`
> 
> ![Powershell](https://user-images.githubusercontent.com/43521247/150640021-3a0eebcd-292e-4d79-b6a1-97e47f1d555d.png)

Hmm, it says drive is already in use but i dont see it in explorer !
Also it's not mapped in screenshots as you think !
A properly mapped Z looks like this

![image](https://user-images.githubusercontent.com/76276047/150640372-88c584f7-0046-4c85-a296-aca11a147c06.png)

The drive should also show up in two places as you see in my screenshot...

Can you please open powershell with: ```python3 -m cassowary -c guest-run -- "powershell.exe``` 
run ```net use```
and ```gdr -PSProvider 'FileSystem'``` and share the output of these commands !

**Comment by Le0xFF** [comment] 2022-01-22 13:40
Oh okay, yeah that look like a proper mapped drive :laughing: 

> run net use
> and gdr -PSProvider 'FileSystem' and share the output of these commands!

![PS](https://user-images.githubusercontent.com/43521247/150640715-2b52b905-68dd-430a-933c-eae4917c0567.png)

**Comment by casualsnek** [comment] 2022-01-22 13:55
Weird Z: drive is not shown in explorer but PS shows like mapping worked !

cah if check if you run: ```net use P: \\tsclient\root\home\leot\Scaricati /persistent:Yes``` 
in powershell the same way does this give system error 87 too or not

and what hets listed if you run
```ls Z:\``` in powershell

**Comment by Le0xFF** [comment] 2022-01-22 14:00
> net use P: \\tsclient\root\home\leot\Scaricati /persistent:Yes

It just works, it says "command correctly executed" and ofc if I try to give that command again it says that the device is already in use.

With `ls` I can see my whole root folder.

![PS2](https://user-images.githubusercontent.com/43521247/150641361-f3f20ac4-8fa2-4af4-829c-54a3779eb336.png)

**Comment by casualsnek** [comment] 2022-01-22 14:13
I just created new release can you check if it solves any of your issue !

Also run ```net use Z: /delete``` and ```net use P: /delete``` before updating !

**Comment by Le0xFF** [comment] 2022-01-22 14:36
Okay, with the new release my initial problem is fixed, yay!
May I suggest you to also add the .exe name beside the App name, maybe even between bracket, so one can clearly know what app is adding!

![GuestAppsWorking](https://user-images.githubusercontent.com/43521247/150642710-cbfe1a75-472a-4e21-9e97-3f33f80542a6.png)

By the way, the app I added has no proper icon, but I don't know if that depends on my distro/DE (VoidLinux/Mate)

![icon](https://user-images.githubusercontent.com/43521247/150642807-f169e463-0485-4bd2-9033-3709b1b0b0a4.png)

---

The other problem tho, the mapping folder one, is not fixed I guess? Because I'm still having the same error 87.

![FolderMappingNotWorking](https://user-images.githubusercontent.com/43521247/150642847-0fee4965-a01f-41fd-b3e8-4881f8dfdd24.png)

**Comment by casualsnek** [comment] 2022-01-22 14:50
> Okay, with the new release my initial problem is fixed, yay! May I suggest you to also add the .exe name beside the App name, maybe even between bracket, so one can clearly know what app is adding!
> 
> ![GuestAppsWorking](https://user-images.githubusercontent.com/43521247/150642710-cbfe1a75-472a-4e21-9e97-3f33f80542a6.png)
> 
> By the way, the app I added has no proper icon, but I don't know if that depends on my distro/DE (VoidLinux/Mate)
> 
> ![icon](https://user-images.githubusercontent.com/43521247/150642807-f169e463-0485-4bd2-9033-3709b1b0b0a4.png)
> 
> The other problem tho, the mapping folder one, is not fixed I guess? Because I'm still having the same error 87.
> 
> ![FolderMappingNotWorking](https://user-images.githubusercontent.com/43521247/150642847-0fee4965-a01f-41fd-b3e8-4881f8dfdd24.png)

The icons are extracted from the exe file on vm itself, can you find paint's icon in  "~/.cache/casualrdh/" ?
I will add exe name in next version !


For the second issue, i will look into it. Since i cannot reproduce it on my system i, i may ask lot of of questions, hope you don't mind it !

**Comment by Le0xFF** [comment] 2022-01-22 14:57
> can you find paint's icon in "~/.cache/casualrdh/" ?

No, i find absolutely nothing there :(

![cache](https://user-images.githubusercontent.com/43521247/150643561-ec99bb4f-1960-497d-8471-403e3a1af2d8.png)

> I may ask lot of of questions, hope you don't mind it!

Absolutely not! I'll try to reply as fast as possible. This project is what Linux users are craving since years and I'd like to contribute and fix most of the stuffs I can :smile:

**Comment by casualsnek** [comment] 2022-01-22 15:05
![image](https://user-images.githubusercontent.com/76276047/150643966-75c191d9-70ed-49f7-b3d1-a1a4ebd01e59.png)

Were you able to see the app icon, after you click add from the GUI ?

**Comment by Le0xFF** [comment] 2022-01-22 15:08
Nope, not at all.

![Paint](https://user-images.githubusercontent.com/43521247/150644066-82632936-fbda-42e6-92c4-fcc3210c644c.png)

**Comment by casualsnek** [comment] 2022-01-22 15:14
I will look into this... can you create separate issue for no icons issue ! It will be easier for other people with similar issue too ! Also i will improve logging first it will make handling issues easier for end user as well as me !

**Comment by Le0xFF** [comment] 2022-01-22 15:38
When I tried to make a shortcut for another application, the icon showed up for the other one!

So I guess the problem is just for MSPaint :laughing: 

I guess I'll get that icon from somewhere else.
![Word](https://user-images.githubusercontent.com/43521247/150645290-f16bb4e6-939c-4d7f-a848-78dc05a9033e.png)
![Word2](https://user-images.githubusercontent.com/43521247/150645292-9695d08e-0c8d-49cc-b18e-78c3ec773756.png)

**Comment by casualsnek** [comment] 2022-01-22 16:24
I suspect the directory sharing issue maybe due to Enterprise LTSC edition, can you share link to the ISO image you are using so i can test it ! ?

**Comment by Le0xFF** [comment] 2022-01-22 16:37
[Here's the link!](https://dweb.link/ipfs/bafybeih4tqwbsoqpl2ip7mcv5ofuynto3xlh4nirkt3m4s3wdz6oph32rq?filename=en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso)

---

Btw, an update about the directory sharing. With the new release my root is now properly and automatically mapped when I open explorer.exe through the command `python3 -m cassowary -c guest-run -- "explorer.exe"`

![explorer](https://user-images.githubusercontent.com/43521247/150647280-2ebe34e5-54ea-4266-bfb4-3f875356acf2.png)

But if I close explorer.exe and I open the cassowary gui, the situation is still the same as before!

![Error](https://user-images.githubusercontent.com/43521247/150647440-1a783026-0b4f-4f18-b812-329a4ab9f971.png)

**Comment by casualsnek** [comment] 2022-01-22 16:46
> i will push an update with more logging.. maybe tomorrow after which i can know what failed ! Since Z: is now mapped i suspect one or two places where it could be breaking !

**Comment by casualsnek** [comment] 2022-01-23 06:13
Since the main issue for this thread was apps not being listed ! I am closing this one and for System Error 87 error while sharing directory discussion should continue here: https://github.com/casualsnek/cassowary/issues/11

**Closed** 2022-01-23 06:14 UTC
Labels: bug

**Comment by casualsnek** [comment] 2022-01-24 11:42
Can you test the v0.3, it should fix this issue properly !

**Comment by Le0xFF** [comment] 2022-01-24 12:06
Yes, it still works even with the new release. Every app is listed and I'm able to add any of them without any issue!
