### ISSUE TITLE
No app icon when creating a desktop shortcut for MSPaint

### ISSUE THREAD

**Issue by Le0xFF** [casualsnek/cassowary#8] opened 2022-01-22 15:47 UTC
Opening a new issue as stated in #6 

---

When I try to make a new desktop shortcut for MSPaint, the icon from the .exe is not saved in `~/.cache/casualrdh` folder, resulting in an iconless menu entry.

![MSPaint1](https://user-images.githubusercontent.com/43521247/150645478-99657101-8a4f-48b3-8438-648292185bb8.png)

---

This does not happen with any other application, such as Microsoft Word.

![Word2](https://user-images.githubusercontent.com/43521247/150645490-0b6bdb5d-33fc-4e60-898b-faad7b8a2237.png)

![Word3](https://user-images.githubusercontent.com/43521247/150645494-34335049-f4b8-4023-93c7-9c099107d60c.png)

**Comment by casualsnek** [comment] 2022-01-22 15:51
can you copy the mspaint.exe from your system and upload and share it ! Some apps like WordPad do not contain Icon, Name, or Version name on their executable for which i can do nothing.. But for paint icon should have been fetched !

**Comment by Le0xFF** [comment] 2022-01-22 15:59
Here it is!
[mspaint.zip](https://github.com/casualsnek/cassowary/files/7918684/mspaint.zip)

**Comment by casualsnek** [comment] 2022-01-22 16:21
> Here it is! [mspaint.zip](https://github.com/casualsnek/cassowary/files/7918684/mspaint.zip)

As i suspected the .exe file itself has no image contained in which case cassowary shows blank icon. My windows 10 mspaint.exe contains icon but maybe Enterprise LTSC's paint does not ! 

What if i made cassowary use a generic app icon/logo for app that do not contain icon in them ?

**Comment by Le0xFF** [comment] 2022-01-22 16:30
I guess it could be the best solution for all the iconless .exe :+1:

**Comment by casualsnek** [comment] 2022-01-23 09:03
This commit should fix the issue: https://github.com/casualsnek/cassowary/commit/da49e44d27f709305b2a00d9e716586e93080f81

It also adds a field to manually specify icon  when creating desktop entry ! 
Binary release will be available after next minor version bump.

You may close the issue if you think the issue is resolved.

**Closed** 2022-01-23 09:06 UTC
